version: '3.8'

services:
  # Redis service for distributed mode
  redis:
    image: redis:7-alpine
    container_name: reactive-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Spring Boot application
  reactive-app:
    build: .
    container_name: reactive-sse-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Redis GUI for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - dev

volumes:
  redis_data:
