apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-sse-local
  labels:
    app: reactive-sse-local
    environment: local
spec:
  replicas: 2  # Start with 2 replicas for local testing
  selector:
    matchLabels:
      app: reactive-sse-local
  template:
    metadata:
      labels:
        app: reactive-sse-local
        environment: local
    spec:
      containers:
      - name: reactive-sse
        image: reactive-sse-app:latest
        imagePullPolicy: Never  # Use local image, don't pull from registry
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: REDIS_HOST
          value: "redis-local-service"
        - name: REDIS_PORT
          value: "6379"
        - name: MONGO_HOST
          value: "mongodb-local-service"
        - name: MONGO_PORT
          value: "27050"
        - name: MONGO_DATABASE
          value: "reactive_messages"
        - name: LOGGING_LEVEL_COM_KAMRUDDIN_REACTIVE
          value: "DEBUG"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: reactive-sse-local-service
  labels:
    app: reactive-sse-local
spec:
  selector:
    app: reactive-sse-local
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reactive-sse-local-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reactive-sse-local
  minReplicas: 1
  maxReplicas: 4  # Reduced for local environment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Higher threshold for local
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
